services:
  deep-research:
    container_name: deep-research
    build: .
    env_file:
      - .env.local
    volumes:
      - ./:/app/
    tty: true
    stdin_open: true
    networks:
      - ksln-ntw

networks:
  ksln-ntw:
    external: true
